-- A PEDIDO (2026-09-29) — atribuição inicial do selo de verificação:
-- a conta oficial do SeenList recebe "gold", e os 99 usuários
-- restantes da lista dos 100 primeiros cadastrados (levantada por
-- consulta SQL direta na tabela, em ordem de created_at) recebem
-- "blue". Idempotente — pode rodar de novo sem duplicar efeito.

-- Gold: conta oficial
update public.profiles
set verified_tier = 'gold'
where username = 'seenlistapp';

-- Blue: 99 primeiros usuários cadastrados após a conta oficial
update public.profiles
set verified_tier = 'blue'
where username in (
  'becamalikson',
  'beatrizdutra97',
  'taniamoleite',
  'gabrielavellar',
  'magnotoninatofarias',
  'prazermuniz',
  'ys14042004',
  'denisevilche',
  'caroolsaantana96',
  'irlyly',
  'lauraverolezi',
  'wendlleylima0',
  'patrickdziura',
  'bella_pathy',
  'rianszimanski',
  'miguelrolo220',
  'shadiamatny',
  'john',
  'pmayl',
  'gabynunessl',
  'dudu3566',
  'thiagodalla',
  'amandaamorandi',
  'nclhdd',
  'braiamsg',
  'terezacaetano1702',
  'mirielenlife',
  'alanmanoelribeiro',
  'marciarlima65',
  'marcosvingoncalves',
  'catarinaluis1897',
  'diariodeumaespectadora',
  'vemanuelle032',
  'jessicamrvasque',
  'hatakesubs',
  'kevincfbrito',
  'denilsonfontenelesjd',
  'isis10karoline',
  'ivaneipereira20',
  'andressabitencourtromanzini',
  'kaiosanchesrodaelli',
  'maryrrib',
  'vivianyamassaki',
  'montenegrothiago95',
  'nascimentoluisa95',
  'myalima',
  'rguima',
  'christianturba02',
  'zzxsworddrake',
  'jornalcamil',
  'daryke',
  'milinh11',
  'sthefanicpaiva',
  'heeygrazi',
  'kelpaes1',
  'mirelaalcantara5',
  'leticiadrieles',
  'paulahelenandrades',
  'flahalmeida',
  'jeffersonluiss2003',
  'oliveiraclucas',
  'luara18melo',
  'bibruy',
  'wellitognpereira',
  'thayanen',
  'kulooarthur',
  'igornascimento7',
  'liviouvicurti',
  'carinadccabral12',
  'claraalves108',
  'carlosousa',
  'johnwiliam',
  'deanlenas',
  'fernandaneubert2012',
  'renan_santana',
  'noellegmt',
  'buenothiagoo',
  'vitoriaxl54',
  'joanabachmann',
  'jerrilandy',
  'natyjxd',
  'tamy2870',
  'manoelnetto',
  'yasmincosta903',
  'yanaanay',
  'isamagalhaesbela',
  'darapanasio',
  'alexejudy',
  'moncefchoukri96',
  'nathyunik',
  'jimindinesh',
  'rubenssamueld',
  'marianaregia21',
  'laovilath',
  'juuo75',
  'aideslucas',
  'eduuardoleal',
  'clteles14',
  'mayracarolinaleal'
);
